### ISSUE TITLE
broken link on main page

### ISSUE THREAD

**Issue by hannesm** [patricoferris/jsoo-mithril#1]
hey,

thanks for your bindings and tutorials :)
I noticed on https://jsoo-mithril.patricoferris.com/ you link to https://jsoo-mithril.patricoferris.com/tutorials (in "The tutorials to help explain the important aspects of the library") -- and that link target returns a 404 -- the side navbar has links to the individual tutorials that work great.

**Comment by patricoferris** [comment]
Thanks for taking the time to report this -- I really appreciate it :)
